/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glumes_instantglsl_CameraRenderer */

#ifndef _Included_com_glumes_instantglsl_CameraRenderer
#define _Included_com_glumes_instantglsl_CameraRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glumes_instantglsl_CameraRenderer
 * Method:    onSurfaceCreated
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_CameraRenderer_onSurfaceCreated
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_glumes_instantglsl_CameraRenderer
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_CameraRenderer_onSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_glumes_instantglsl_CameraRenderer
 * Method:    onSurfaceDestroyed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_CameraRenderer_onSurfaceDestroyed
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_instantglsl_CameraRenderer
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_CameraRenderer_draw
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_instantglsl_CameraRenderer
 * Method:    getTextureId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_glumes_instantglsl_CameraRenderer_getTextureId
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_instantglsl_CameraRenderer
 * Method:    swapBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_CameraRenderer_swapBuffers
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_instantglsl_CameraRenderer
 * Method:    shaderChange
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_CameraRenderer_shaderChange
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
