/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glumes_instantglsl_InstantRenderer */

#ifndef _Included_com_glumes_instantglsl_InstantRenderer
#define _Included_com_glumes_instantglsl_InstantRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glumes_instantglsl_InstantRenderer
 * Method:    init
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_InstantRenderer_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_glumes_instantglsl_InstantRenderer
 * Method:    renderer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_InstantRenderer_renderer
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_instantglsl_InstantRenderer
 * Method:    shaderChange
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_InstantRenderer_shaderChange
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_glumes_instantglsl_InstantRenderer
 * Method:    textureChange
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_InstantRenderer_textureChange__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_glumes_instantglsl_InstantRenderer
 * Method:    textureChange
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_InstantRenderer_textureChange__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_glumes_instantglsl_InstantRenderer
 * Method:    reportError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_InstantRenderer_reportError
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_instantglsl_InstantRenderer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_instantglsl_InstantRenderer_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

